=== chanda100/ibm-ace-integration-portfolio/SchoolServicesLib/StudentInfo.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="student">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="studentId" type="xsd:string" />
                <xsd:element name="firtName" type="xsd:string" />
                <xsd:element name="lastName" type="xsd:string" />
                <xsd:element name="dateOfBirth" type="xsd:string" />
                <xsd:element name="studentEmail" type="xsd:string" />
                <xsd:element name="guardianContactName" type="xsd:string" />
                <xsd:element name="guardianContactNo" type="xsd:string" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== chanda100/ibm-ace-integration-portfolio/SchoolServicesLib/TestStudent.xml
<?xml version="1.0" encoding="UTF-8"?><student xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="StudentInfo.xsd">  <studentId>123</studentId>  <firtName>test first name</firtName>  <lastName>test last name</lastName><dateOfBirth>22/2/2026</dateOfBirth><studentEmail>abc@gmail.com</studentEmail><guardianContactName>test Parent</guardianContactName><guardianContactNo>1212phoneno</guardianContactNo></student>
